---
title: "Dry_Creek_T"
author: "Tao Huang"
date:  "`r  Sys.time() `"
output:
  pdf_document: default
  html_document: default
---

# The 'tidyverse' is a set of packages.
```{r, hide=T, results='hide'}
library("tidyverse")
getwd()
```

https://www.boisestate.edu/drycreek/dry-creek-data/lower-gauge/#historical-data

# Download data for multiple years
```{r}
yr=c(2004:2022)
for (year in yr) {
url=paste("https://icewater.boisestate.edu/boisefront-products/historical/dcew_lg/StreamHourlyData/LG_StreamHrlySummary_",year,".csv",sep="")
destfile=paste("LG_StreamHrlySummary_",year,".csv",sep="")
download.file(url, destfile)
}
```


```{r}
df<-data.frame(DateTime=as.POSIXct("2000-01-01 00:00:00"), Discharge=0, StreamTemp=0, StreamEC=as.factor(0)
)
for (year in yr) {
destfile=paste("LG_StreamHrlySummary_",year,".csv",sep="")
#read data
f<-read.csv(destfile)
f2<-f[c(18:dim(f)[1]),c(1:4)]
f2[1,]
colnames(f2 )<-unlist(f2[1,])
#colnames(f2 )<-as.character(f2[1,])
f2<-f2[-1,]
#f2$DateTime<-as.character(f2$DateTime)
f2$DateTime<-as.POSIXct(f2$DateTime, format="%m/%d/%Y %H:%M")
f2$DateTime
f2$`Discharge-L/s`<-as.numeric(as.character(f2$`Discharge-L/s`))
f2$`StreamTemp-C` <-as.numeric(as.character(f2$`StreamTemp-C`))
colnames(f2)<-c("DateTime" ,  "Discharge" , "StreamTemp", "StreamEC")
df<-rbind(f2,df)
}
head(df)
```

```{r}
df2<-df[!df$StreamTemp<=-6999 & !df$Discharge <=-6999 ,]
df2_summer<-df2[ months( df2$DateTime) %in% c("June","July","August") ,]
plot(df2$Discharge ,df2$StreamTemp)
plot(df2_summer$Discharge ,df2_summer$StreamTemp)
plot(df2$DateTime,df2$StreamTemp)
```

https://www.boisestate.edu/drycreek/dry-creek-data/lower-weather/#historical-data
```{r}

yr=c(2016:2019)
for (year in yr) {
url=paste("https://icewater.boisestate.edu/boisefront-products/historical/dcew_lw/Weather/4CompRadiation/LW_4CompRadHrlySummary_",year,".csv",sep="")
destfile=paste("LW_4CompRadHrlySummary_",year,".csv",sep="")
download.file(url, destfile)
}

```

```{r}
getwd()
list.files()
destfile
r<-read.csv(destfile)
r
```


```{r}
rad_df<-data.frame(DateTime=as.POSIXct("2000-01-01 00:00:00"), Discharge=0, StreamTemp=0, StreamEC=as.factor(0)
)
for (year in yr) {
destfile=paste("LG_StreamHrlySummary_",year,".csv",sep="")
#read data
f<-read.csv(destfile)
f2<-f[c(18:dim(f)[1]),c(1:4)]
f2[1,]
colnames(f2 )<-unlist(f2[1,])
#colnames(f2 )<-as.character(f2[1,])
f2<-f2[-1,]
#f2$DateTime<-as.character(f2$DateTime)
f2$DateTime<-as.POSIXct(f2$DateTime, format="%m/%d/%Y %H:%M")
f2$DateTime
f2$`Discharge-L/s`<-as.numeric(as.character(f2$`Discharge-L/s`))
f2$`StreamTemp-C` <-as.numeric(as.character(f2$`StreamTemp-C`))
colnames(f2)<-c("DateTime" ,  "Discharge" , "StreamTemp", "StreamEC")
df<-rbind(f2,df)
}
head(df)
```









<!-- # Plot T vs. Q -->
<!-- ```{r} -->
<!-- plot(f_summer$`Discharge-L/s`,f_summer$`StreamTemp-C`) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- p <- ggplot(f_summer, aes(`Discharge-L/s` , `StreamTemp-C` )) -->
<!-- p + geom_point() -->
<!-- ``` -->
