---
title: "Dry_Creek_T"
author: "Tao Huang"
date:  "`r  Sys.time() `"
output:
  pdf_document: default
  html_document: default
---

This .RMD downloads stream T and Q from the Bogus South Gage; Weather Station Data from Bogus Ridge.

# The 'tidyverse' is a set of packages.
```{r, hide=T, results='hide'}
library("lubridate")
library("dplyr")
#install.packages('corrplot')
library(corrplot)
library(RColorBrewer)
# install.packages("gbm")
library("gbm")
# install.packages("caret")
library("caret")
#install.packages("pdp")
library("pdp")          # model visualization
library("ggplot2")      # model visualization
#install.packages("lime")
library("lime")         # model visualization
library("pROC")
#install.packages("e1071", repos="http://R-Forge.R-project.org")
library("e1071")
library( "MASS" )    #    used to generate correlated variables
library("sp")
# install.packages("Hmisc")
library("Hmisc")    #   used for graphing se bars
#install.packages("randomForest")
require("randomForest")
#install.packages("e1071")
library(e1071)
library(caret)
library("ModelMetrics")
library("foreign")
#install.packages("rfUtilities")
library("rfUtilities")
# install.packages("pls")
library(pls)
```

https://www.boisestate.edu/drycreek/dry-creek-data/bogus-south/#historical-data
2006-2020

# Download data for multiple years (Bogus South Gage)
```{r , hide=T, results='hide' }
yr=c(2006:2020)
site="BSG"
for (year in yr) {
url=paste("https://icewater.boisestate.edu/boisefront-products/historical/dcew_bsg/StreamHourlyData/",site,"_StreamHrlySummary_",year,".csv",sep="")
destfile=paste(site,"_StreamHrlySummary_",year,".csv",sep="")
download.file(url, destfile)
}
```

```{r}
df<-data.frame(DateTime=as.POSIXct("1000-01-01 00:00:00"), Discharge=0, StreamTemp=0, StreamEC=as.factor(0))

yr=c(2006:2012,2014:2017, 2019:2020)      #2013 and 2018 year in %y not %Y

for (year in yr) { 
destfile=paste(site,"_StreamHrlySummary_",year,".csv",sep="")
f<-read.csv(destfile)
f2<-f[c(18:dim(f)[1]),c(1:4)]
f2[1,]
colnames(f2 )<-unlist(f2[1,])
f2<-f2[-1,]
f2$DateTime<-as.POSIXct(f2$DateTime, format="%m/%d/%Y %H:%M")
f2$DateTime
f2$`Discharge-L/s`<-as.numeric(as.character(f2$`Discharge-L/s`))
f2$`StreamTemp-C` <-as.numeric(as.character(f2$`StreamTemp-C`))
colnames(f2)<-c("DateTime" ,  "Discharge" , "StreamTemp", "StreamEC")

#if ( min(as.numeric(format( f2$DateTime,"%Y")), na.rm=T) <2000         )
#{print(year)}

df<-rbind(f2,df)
}

head(df)
df2<-df[!df$StreamTemp<=-6999 & !df$Discharge <=-6999 & !is.na(df$DateTime) ,]
summary(df2)
```


```{r}
df3<-df2[df2$DateTime>=as.Date("2000-01-01",format="%Y-%m-%d"),]
#save( df3  ,file=paste(site,"df3.Rdata",sep="_"))
```


```{r}
site="BSG"
load( paste(site,"df3.Rdata",sep="_"))
```

Meteorological Variables
2011-2020
https://www.boisestate.edu/drycreek/dry-creek-data/bogus-ridge/#historical-data

```{r}
yr=c(2011:2020)
site="BRW"
for (year in yr) {
url=paste("https://icewater.boisestate.edu/boisefront-products/historical/dcew_br/Weather/Hourly%20Summary%20Data/",site,"_HrlySummary_",year,".csv",sep="")
destfile=paste(site,"_HrlySummary_",year,".csv",sep="")
download.file(url, destfile)
}
```

```{r}
met_df<-data.frame(DateTime=as.POSIXct("1000-01-01 00:00:00"),Precipitation_mm=0,         AirTemperature_C =0, SolarRadiation =0,NetRadiation =0,RelativeHumidity_percent=0,WindDirection_degree=0,WindSpeed =0, SnowDepth_cm    =0 )

yr=c(2011:2018,2020)

for (year in yr) {
destfile=paste(site,"_HrlySummary_",year,".csv",sep="")
r<-read.csv(destfile, header=F)
r2<-r[c(20:dim(r)[1]),c(1:9)]
colnames(r2)<-r2[1,]
r2<-r2[-1,]
head(r2)
r2$DateTime<-as.POSIXct(r2$DateTime , format="%m/%d/%Y %H:%M")
colnames(r2)<-c( "DateTime" ,"Precipitation_mm" , "AirTemperature_C"  , "SolarRadiation" ,"NetRadiation" ,"RelativeHumidity_percent" ,"WindDirection_degree" ,"WindSpeed" , "SnowDepth_cm" )

air_summary<-summary((as.numeric(  r2$AirTemperature_C  ) ))
# 
# if (  air_summary[2] < -100         )
# {print(year)}


met_df<-rbind(r2,met_df)
}

head(met_df)
summary(met_df)
```

```{r}
met_df[,c( "Precipitation_mm" , "AirTemperature_C"  , "SolarRadiation" ,"NetRadiation" ,"RelativeHumidity_percent" ,"WindDirection_degree" ,"WindSpeed" , "SnowDepth_cm")]  <- sapply( met_df[,c( "Precipitation_mm" , "AirTemperature_C"  , "SolarRadiation" ,"NetRadiation" ,"RelativeHumidity_percent" ,"WindDirection_degree" ,"WindSpeed" , "SnowDepth_cm")] ,as.numeric)
summary(met_df)
```

```{r}
met_df2 <-met_df[!met_df$AirTemperature_C <= -100 &   !met_df$SolarRadiation       <=-6999 & !is.na(met_df$DateTime) ,]
summary(met_df2)
save(met_df2,file="met_df2.Rdata")
```

# daily
```{r}
df2<-df3
df2$date<-as.Date(df2$DateTime)
met_df2$date<-as.Date(met_df2$DateTime)
daily<-merge(df2 ,met_df2 ,by="date")

daily_df <- daily %>%                            
group_by(date) %>%
summarize(min_Discharge = min(Discharge) , median_Discharge = median( Discharge) ,   max_Discharge = max( Discharge),
          min_StreamTemp = min(StreamTemp) , median_StreamTemp = median(StreamTemp) ,   max_StreamTemp = max(StreamTemp),
          min_AirTemperature_C = min(AirTemperature_C) , median_AirTemperature_C = median(AirTemperature_C) ,   max_AirTemperature_C = max(AirTemperature_C),
          min_SolarRadiation = min(SolarRadiation) , median_SolarRadiation = median(SolarRadiation) ,   max_SolarRadiation = max(SolarRadiation)
          )

daily_df<-daily_df[daily_df$min_Discharge>0,]

daily_df_summer<-daily_df[    months( daily_df$date ) %in% c("June","July","August")   ,]
summary(daily_df_summer)
save(daily_df_summer, file="daily_df_summer.Rdata")
```

```{r}
load("daily_df_summer.Rdata")
daily_df_summer$doy<- yday(daily_df_summer$date)
daily_df_summer$log_median_Q<-log(daily_df_summer$median_Discharge)
```

```{r}
M <-cor(daily_df_summer[,c( 3,7 )])
corrplot(M
         #, type="upper", order="hclust",
         #col=brewer.pal(n=8, name="RdYlBu")
         )
```


# Model 2: GBM
```{r}
# set seed for generating random data.
set.seed(0)          
# createDataPartition() function from the caret package to split the original dataset into a training and testing set and split data into training (80%) and testing set (20%)
variables<-c("max_StreamTemp","log_median_Q"
             #,"min_Discharge"
             ,"max_AirTemperature_C", "max_SolarRadiation",   "doy")
parts = createDataPartition(  daily_df_summer$max_StreamTemp , p = .8, list = F)
train = daily_df_summer[parts, variables ]
test =  daily_df_summer[-parts, variables  ]
# feature and target array
test_x = test[, -1] 
test_y = test[, 1] 
```


```{r}
model_gbm = gbm(train$max_StreamTemp      ~.,
                data = train,
                distribution = "gaussian",
                cv.folds = 10,
                shrinkage = .01,
                n.minobsinnode = 10,
                n.trees = 800)
 
# model performance
perf_gbm1 = gbm.perf( model_gbm, method = "cv")
print(model_gbm)
summary(model_gbm)
rinf<-summary(model_gbm)
barplot( rinf$rel.inf , horiz = TRUE, las = 1)
ggplot(rinf, aes(rel.inf)) + geom_bar()
```


```{r}
rinf$var<- factor(rinf$var, levels=c(  "max_AirTemperature_C" ,"log_median_Q"
             #,"min_Discharge"
             ,      "max_SolarRadiation" ,
             "doy"  ))
ggplot( rinf, aes( var , rel.inf ))+  geom_col()+ 
  coord_flip()
ggplot( rinf )+  geom_bar(  aes( x=var, y= rel.inf),  stat = "summary")+ scale_x_discrete(labels=  c( "max_AirTemperature_C" ,"log_median_Q"
             #,"min_Discharge"
             ,      "max_SolarRadiation" , 
             "doy") )+ylab("Relative importance (%)") +xlab(" ")  + theme(text=element_text(size=11))
```


```{r}
#test_y <-test_y$max_StreamTemp
pred_y = predict.gbm(model_gbm, test_x)
residuals =  test_y   - pred_y
summary(test_y )
xlim=c(5,20)
RMSE = sqrt(mean(residuals^2))
cat('The root mean square error of the test data is ', round(RMSE,3),'\n')
y_test_mean = mean( test_y  )
# Calculate total sum of squares
tss =  sum(( test_y   - y_test_mean)^2 )
# Calculate residual sum of squares
rss =  sum(residuals^2)
# Calculate R-squared
rsq  =  1 - (rss/tss)
cat('The R-square of the test data is ', round(rsq,3), '\n')
# visualize the model, actual and predicted data
x_ax = 1:length(pred_y)
plot(x_ax, test_y  , col="blue", pch=20, cex=.9)
lines(x_ax, pred_y, col="red", pch=20, cex=.9) 
plot(  test_y , pred_y,xlim= xlim ,ylim= xlim, xlab="Observed stream temperature (degC)", ylab="Predicted stream temperature (degC)", main="GBM")
par(new=T)
x=seq(1,30)
plot(x,x,type="l",xlim= xlim ,ylim= xlim,xlab="",ylab="")
```


```{r}
model_gbm %>%
  partial(pred.var =  "max_AirTemperature_C"   , n.trees = model_gbm$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = train)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24))

#,"min_Discharge"

model_gbm %>%
  partial(pred.var =  "log_median_Q"
             #,"min_Discharge"
               , n.trees = model_gbm$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = train)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24))
```














```{r}
summary( lm(daily_df_summer$max_StreamTemp ~ log(daily_df_summer$max_Discharge ) +    (daily_df_summer $max_AirTemperature_C ) + daily_df_summer$max_SolarRadiation) )
```


```{r}
daily_df_summer_2020<-daily_df_summer[daily_df_summer$date>=as.Date("2020-01-01",format="%Y-%m-%d"),]
daily_df_summer_2020
plot(daily_df_summer_2020$date, daily_df_summer_2020$max_SolarRadiation)
plot(daily_df_summer_2020$date, daily_df_summer_2020$max_Discharge)
plot(daily_df_summer_2020$date, daily_df_summer_2020$max_StreamTemp)
plot(daily_df_summer_2020$date, daily_df_summer_2020$max_AirTemperature_C )
```












```{r}
df2_summer<-df2[ months( df2$DateTime) %in% c( "June","July","August" ) ,]
df2_summer_2020<-df2_summer[ df2_summer$DateTime>=as.Date("2020-01-01",format="%Y-%m-%d") ,]
df2_summer_2020
plot(df2_summer_2020$DateTime, log(df2_summer_2020$Discharge))
plot(df2_summer_2020$DateTime,  df2_summer_2020$StreamTemp )
```

```{r}
plot(df2$Discharge ,df2$StreamTemp)
plot(log(df2_summer$Discharge) ,df2_summer$StreamTemp)
plot(df2$DateTime,df2$StreamTemp)
hist( log(df2_summer$Discharge) )
hist( df2_summer$StreamTemp)
```



```{r}
yr=c(2012:2019)
site="BRW"
for (year in yr) {
url=paste("https://icewater.boisestate.edu/boisefront-products/historical/dcew_br/Weather//4%20CompRadiation/",site,"_4CompRadHrlySummary_",year,".csv",sep="")
destfile=paste(site,"_4CompRadHrlySummary_",year,".csv",sep="")
download.file(url, destfile)
}
```

<!-- ```{r} -->
<!-- getwd() -->
<!-- list.files() -->
<!-- destfile -->
<!-- r<-read.csv(destfile, header=F) -->
<!-- r2<-r[c(20:dim(r)[1]),c(1:6)] -->
<!-- colnames(r2)<-r2[1,] -->
<!-- r2<-r2[-1,] -->
<!-- ``` -->

```{r}
rad_df<-data.frame(DateTime=as.POSIXct("1000-01-01 00:00:00"), SWin=0, SWout=0, LWin=0, LWout=0, RadTemp=0)
for (year in yr) {
destfile=paste(site,"_4CompRadHrlySummary_",year,".csv",sep="")

r<-read.csv(destfile, header=F)
r2<-r[c(19:dim(r)[1]),c(1:6)]
colnames(r2)<-r2[1,]
r2<-r2[-1,]
r2$DateTime<-as.POSIXct(r2$DateTime , format="%m/%d/%Y %H:%M")
colnames(r2)<-c("DateTime", "SWin" , "SWout" , "LWin" , "LWout" , "RadTemp")
  
rad_df<-rbind(r2,rad_df)
}
head(rad_df)
summary(rad_df)
```

```{r}
#rad_df %>%  mutate(across(c( "SWin" , "SWout" , "LWin" , "LWout" , "RadTemp"),  function(x) as.numeric(x)))

rad_df[,c( "SWin" , "SWout" , "LWin" , "LWout" , "RadTemp")]  <- sapply( rad_df[,c( "SWin" , "SWout" , "LWin" , "LWout" , "RadTemp")] ,as.numeric)

#rad_df %>% mutate_if(is.character,as.numeric)

#rad_df %>% mutate_at(c( "SWin" , "SWout" , "LWin" , "LWout" , "RadTemp"), as.numeric)

summary(rad_df)
```

```{r}
rad_df2 <-rad_df[!rad_df$SWout        <=-6999 & !rad_df$SWin      <=-6999 & !is.na(rad_df$DateTime) ,]
#save(rad_df2,file="rad_df2.Rdata")

```

```{r}
#load("rad_df2.Rdata")
rad_df2_summer<-rad_df2[ months( rad_df2$DateTime) %in% c("June","July","August") ,]
rad_df2_summer
```

```{r}
plot(rad_df2_summer$DateTime, rad_df2_summer$RadTemp)

plot(rad_df2_summer$SWin, rad_df2_summer$RadTemp)

plot(rad_df2_summer$SWout , rad_df2_summer$RadTemp)

plot(rad_df2_summer$LWout , rad_df2_summer$RadTemp)

plot(rad_df2_summer$LWin  , rad_df2_summer$RadTemp)

```

# daily
```{r}
df2$date<-as.Date(df2$DateTime)
rad_df2$date<-as.Date(rad_df2$DateTime)
daily<-merge(df2 ,rad_df2 ,by="date")

daily_df <- daily %>%                            
group_by(date) %>%
summarize(min_Discharge = min(Discharge) , median_Discharge = median( Discharge) ,   max_Discharge = max( Discharge),
          min_StreamTemp = min(StreamTemp) , median_StreamTemp = median(StreamTemp) ,   max_StreamTemp = max(StreamTemp),
          min_SWin = min(SWin) , median_SWin = median(SWin) ,   max_SWin = max(SWin),
          min_SWout = min(SWout) , median_SWout = median(SWout) ,   max_SWout = max(SWout)
          )

daily_df<-daily_df[daily_df$min_Discharge>0,]

daily_df_summer<-daily_df[    months( daily_df$date ) %in% c("June","July","August")   ,]
```

```{r}
summary( lm(daily_df_summer$max_StreamTemp ~ log(daily_df_summer$max_Discharge ) +    (daily_df_summer$max_SWin ) ) )
hist(log(daily_df_summer$max_SWin ))
plot( daily_df_summer$min_Discharge, daily_df_summer$min_StreamTemp)

plot( daily_df_summer$max_SWin, daily_df_summer$max_StreamTemp)
```

```{r}
daily_df_summer_2020<-daily_df_summer[daily_df_summer$date>=as.Date("2020-01-01",format="%Y-%m-%d"),]
daily_df_summer_2020
plot(daily_df_summer_2020$date, daily_df_summer_2020$max_SWout)
plot(daily_df_summer_2020$date, daily_df_summer_2020$max_SWin )
plot(daily_df_summer_2020$date, daily_df_summer_2020$max_Discharge)
plot(daily_df_summer_2020$date, daily_df_summer_2020$max_StreamTemp)


```














```{r}
summer<-merge(df2_summer,rad_df2_summer,by="DateTime")
summer<-summer[summer$Discharge>0,]
```

```{r}
summary( lm(summer$StreamTemp~ log(summer$Discharge) +  summer$SWin  ) )
plot(summer$Discharge, summer$StreamTemp)
plot(summer$SWin, summer$StreamTemp)
```
