---
title: "R Notebook"
output: html_notebook
---

https://www.lobdata.com.br/2020/09/15/how-to-perform-correlation-analysis-in-time-series-data-using-r/

```{r}
#  install.packages("feasts")
library(feasts)
library(tsibble)
library(lubridate)

#  install.packages("TSstudio")
library(TSstudio)
library(plotly)

# third approach
library(tidyverse)
#install.packages("timetk")
library(timetk)
library(lubridate)
```

```{r}
#load("LowerWeather_daily_df_summer.Rdata")
summary(daily_df_summer)
head(daily_df_summer)
```

```{r}
daily_df_summer_2018<-daily_df_summer[daily_df_summer$date>=as.Date("2018-06-01",format="%Y-%m-%d") &
                                        daily_df_summer$date<=as.Date("2018-08-31",format="%Y-%m-%d"),]
daily_df_summer_2018
```

```{r}

ts <- ts(data = daily_df_summer_2018[, c("max_StreamTemp","max_AirTemperature_C" )], # selecting 2 variables
   start = 1,
   end = 90,
   frequency = 1)
ts
```

```{r}



ts_plot( ts,
        title = " ",
        Ytitle = " ",
        Xtitle = " ")




```

```{r}
ts_lags( ts,
        lags = c(0, 1, 4, 6 )) %>% # choosing what lags to plot
  layout(title = "Series vs Lags")
```


```{r}
# ccf time series
par(mfrow=c(1,1))
ccf( ts[, c( "max_StreamTemp"  )],  ts[, c(  "max_AirTemperature_C")], 
    lag.max = 7,
    main = "Cros-Correlation Plot",
    ylab = "CCF")

```

