---
title: "models"
author: "Tao"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r include=FALSE}
library("lubridate")
library("dplyr")
#install.packages('corrplot')
library(corrplot)
library(RColorBrewer)
# install.packages("gbm")
library("gbm")
# install.packages("caret")
library("caret")
#install.packages("pdp")
library("pdp")          # model visualization
library("ggplot2")      # model visualization
#install.packages("lime")
library("lime")         # model visualization
library("pROC")
#install.packages("e1071", repos="http://R-Forge.R-project.org")
library("e1071")
library( "MASS" )    #    used to generate correlated variables
library("sp")
# install.packages("Hmisc")
library("Hmisc")    #   used for graphing se bars
#install.packages("randomForest")
require("randomForest")
#install.packages("e1071")
library(e1071)
library(caret)
library("ModelMetrics")
library("foreign")
#install.packages("rfUtilities")
library("rfUtilities")
```

# Load data and add site
```{r, results='hide'}
site<-read.dbf("DCEWsites2013.dbf")
site<-site[,c("SITE" ,"SITETYPE" ,"DECLAT" ,"DECLONG" ,"ELEV__M_" ,"VERTDATUM")]
summary(site)

load("LowerWeather_daily_df_summer.Rdata")
daily_df_summer_LG<-daily_df_summer
daily_df_summer_LG$SITE<-"DCEW_Lower Gage"
daily_df_summer_LG<-merge(daily_df_summer_LG, site,by="SITE" )
summary(daily_df_summer_LG)

load("daily_df_summer.Rdata")
daily_df_summer_BSG<-daily_df_summer
daily_df_summer_BSG$SITE<-"DCEW_BogusS Gage"
daily_df_summer_BSG<-merge(daily_df_summer_BSG, site,by="SITE" )
summary(daily_df_summer_BSG)

daily_df_summer<-rbind(daily_df_summer_LG, daily_df_summer_BSG)
daily_df_summer$doy<-yday(daily_df_summer$date)
daily_df_summer
```

```{r}
ggplot(daily_df_summer, aes(x= doy, y= max_StreamTemp, color= SITE)) + geom_point()
ggplot(daily_df_summer, aes(x= doy, y=max_AirTemperature_C  , color= SITE)) + geom_point()
ggplot(daily_df_summer, aes(x= doy, y=min_Discharge  , color= SITE)) + geom_point()
ggplot(daily_df_summer[daily_df_summer$SITE=="DCEW_BogusS Gage",], aes(x= doy, y=min_Discharge  , color= SITE)) + geom_point()
```

```{r}
M <-cor(daily_df_summer[,c(3:14,18,20)])
corrplot(M, type="upper", order="hclust",
         col=brewer.pal(n=8, name="RdYlBu"))
#stream T, Air T, DISCHARGE
```

```{r}
hist(daily_df_summer$max_StreamTemp)

hist(log(daily_df_summer$min_Discharge))

hist(daily_df_summer$max_SolarRadiation)

```



<!-- ```{r} -->
<!-- summary(lm(daily_df_summer$max_StreamTemp~ daily_df_summer$min_Discharge + daily_df_summer$max_AirTemperature_C +daily_df_summer$max_SolarRadiation+  daily_df_summer$ELEV__M_+daily_df_summer$doy) ) -->
<!-- summary(lm(daily_df_summer$max_StreamTemp~ log(daily_df_summer$min_Discharge) + daily_df_summer$max_AirTemperature_C +daily_df_summer$max_SolarRadiation +  daily_df_summer$ELEV__M_+daily_df_summer$doy) ) -->
<!-- summary(lm(daily_df_summer$max_StreamTemp~ log(daily_df_summer$min_Discharge) + daily_df_summer$max_AirTemperature_C +  daily_df_summer$ELEV__M_+daily_df_summer$doy  ) ) -->
<!-- ``` -->

# Model 2: GBM
```{r}
# set seed for generating random data.
set.seed(0)          
# createDataPartition() function from the caret package to split the original dataset into a training and testing set and split data into training (80%) and testing set (20%)
variables<-c("max_StreamTemp","min_Discharge","max_AirTemperature_C", "max_SolarRadiation", "ELEV__M_", "doy")
parts = createDataPartition(  daily_df_summer$max_StreamTemp , p = .8, list = F)
train = daily_df_summer[parts, variables ]
test =  daily_df_summer[-parts, variables  ]
# feature and target array
test_x = test[, -1] 
test_y = test[, 1] 
```

# Model 1: lm
```{r}
lm<-lm( max_StreamTemp ~min_Discharge+max_AirTemperature_C+max_SolarRadiation+ELEV__M_+doy , data =  train  )
summary(lm)
mean(lm$residuals^2)
predict<-predict(lm, test_x)
summary(test_y)
xmin=5
xmax=30
x=seq(xmin-5,xmax+5)
plot( test_y ,predict,xlim=c(xmin,xmax) ,ylim=c(xmin,xmax), xlab="Observed stream temperature (degC)", ylab="Predicted stream temperature (degC)")
par(new=T)
plot(x,x,type="l",xlim=c(xmin,xmax) ,ylim=c(xmin,xmax),xlab="",ylab="", main="LM")
```


```{r}
model_gbm = gbm(train$max_StreamTemp      ~.,
                data = train,
                distribution = "gaussian",
                cv.folds = 10,
                shrinkage = .01,
                n.minobsinnode = 10,
                n.trees = 800)
 
# model performance
perf_gbm1 = gbm.perf( model_gbm, method = "cv")
print(model_gbm)
summary(model_gbm)
rinf<-summary(model_gbm)
barplot( rinf$rel.inf , horiz = TRUE, las = 1)
ggplot(rinf, aes(rel.inf)) + geom_bar()
```

```{r}
rinf$var<- factor(rinf$var, levels=c(  "max_AirTemperature_C" ,"min_Discharge"  ,      "max_SolarRadiation" ,"ELEV__M_" , "doy"  ))
ggplot( rinf, aes( var , rel.inf ))+  geom_col()+ 
  coord_flip()
ggplot( rinf )+  geom_bar(  aes( x=var, y= rel.inf),  stat = "summary")+ scale_x_discrete(labels=  c( "max_AirTemperature_C" ,"min_Discharge"  ,      "max_SolarRadiation" , "ELEV__M_", "doy") )+ylab("Relative importance (%)") +xlab(" ")  + theme(text=element_text(size=21))
```

```{r}
#test_y <-test_y$max_StreamTemp
pred_y = predict.gbm(model_gbm, test_x)
residuals =  test_y   - pred_y
summary(test_y )
xlim=c(5,30)
RMSE = sqrt(mean(residuals^2))
cat('The root mean square error of the test data is ', round(RMSE,3),'\n')
y_test_mean = mean( test_y  )
# Calculate total sum of squares
tss =  sum(( test_y   - y_test_mean)^2 )
# Calculate residual sum of squares
rss =  sum(residuals^2)
# Calculate R-squared
rsq  =  1 - (rss/tss)
cat('The R-square of the test data is ', round(rsq,3), '\n')
# visualize the model, actual and predicted data
x_ax = 1:length(pred_y)
plot(x_ax, test_y  , col="blue", pch=20, cex=.9)
lines(x_ax, pred_y, col="red", pch=20, cex=.9) 
plot(  test_y , pred_y,xlim= xlim ,ylim= xlim, xlab="Observed stream temperature (degC)", ylab="Predicted stream temperature (degC)", main="GBM")
par(new=T)
x=seq(1,30)
plot(x,x,type="l",xlim= xlim ,ylim= xlim,xlab="",ylab="")
```

```{r}
model_gbm %>%
  partial(pred.var =  "max_AirTemperature_C"   , n.trees = model_gbm$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = train)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24))

#,"min_Discharge"

model_gbm %>%
  partial(pred.var =  "min_Discharge"   , n.trees = model_gbm$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = train)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24))
```


plsr

gvlma

QQ PLOT

LOO PRESS stats

svm
