---
title: "Untitled"
output: html_document
---

Time Series Forecasting with Recurrent Neural Networks

```{r}
library(tibble)
library(readr)
```

```{r}
load("daily_df_summer.Rdata")
daily_df_summer

```

```{r}
# we’ll discard the first column which included a text timestamp 
daily_df_summer_2020 <-daily_df_summer[daily_df_summer$date>=as.Date("2020-01-01", format="%Y-%m-%d" ),]
daily_df_summer_2020<- data.matrix(daily_df_summer_2020[,-1])
daily_df_summer_2020
```

```{r}
#You’re going to use the first 60 timesteps as training data, so compute the mean and standard deviation for normalization only on this fraction of the data.

train_data <- daily_df_summer_2020[1:60,]
mean <- apply(train_data, 2, mean)
std <- apply(train_data, 2, sd)
daily_df_summer_2020 <- scale(daily_df_summer_2020, center = mean, scale = std)
daily_df_summer_2020
```

```{r}
generator <- function(data, lookback, delay, min_index, max_index,
                      shuffle = FALSE, batch_size = 128, step = 6) {
  if (is.null(max_index))
    max_index <- nrow(data) - delay - 1
  i <- min_index + lookback
  function() {
    if (shuffle) {
      rows <- sample(c((min_index+lookback):max_index), size = batch_size)
    } else {
      if (i + batch_size >= max_index)
        i <<- min_index + lookback
      rows <- c(i:min(i+batch_size-1, max_index))
      i <<- i + length(rows)
    }

    samples <- array(0, dim = c(length(rows),
                                lookback / step,
                                dim(data)[[-1]]))
    targets <- array(0, dim = c(length(rows)))
                      
    for (j in 1:length(rows)) {
      indices <- seq(rows[[j]] - lookback, rows[[j]]-1,
                     length.out = dim(samples)[[2]])
      samples[j,,] <- data[indices,]
      targets[[j]] <- data[rows[[j]] + delay,2]
    }           
    list(samples, targets)
  }
}
```

```{r}
lookback <- 40
step <- 1
delay <- 1
batch_size <- 128

train_gen <- generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 1,
  max_index = 60,
  shuffle = TRUE,
  step = step, 
  batch_size = batch_size
)

val_gen = generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 61,
  max_index = 90,
  step = step,
  batch_size = batch_size
)

test_gen <- generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 89,
  max_index = NULL,
  step = step,
  batch_size = batch_size
)

# How many steps to draw from val_gen in order to see the entire validation set
val_steps <- (90 - 60 - lookback) / batch_size

# How many steps to draw from test_gen in order to see the entire test set
test_steps <- (nrow(data) - 90 - lookback) / batch_size
```

```{r}
#install.packages("devtools")
#devtools::install_github("rstudio/keras")
library(keras)
evaluate_naive_method <- function() {
  batch_maes <- c()
  for (step in 1:val_steps) {
    c(samples, targets) %<-% val_gen()
    preds <- samples[,dim(samples)[[2]],2]
    mae <- mean(abs(preds - targets))
    batch_maes <- c(batch_maes, mae)
  }
  print(mean(batch_maes))
}

evaluate_naive_method()
```

```{r}
library(keras)

model <- keras_model_sequential() %>% 
  layer_flatten(input_shape = c(lookback / step, dim(data)[-1])) %>% 
  layer_dense(units = 32, activation = "relu") %>% 
  layer_dense(units = 1)

model %>% compile(
  optimizer = optimizer_rmsprop(),
  loss = "mae"
)

history <- model %>% fit_generator(
  train_gen,
  steps_per_epoch = 500,
  epochs = 20,
  validation_data = val_gen,
  validation_steps = 1 #-0.078125 #val_steps
)
```

